name: "CI Action"
description: "Set up Nix, direnv environment, and uv cache"

inputs:
  github_access_token:
    required: true

runs:
  using: "composite"

  steps:

    - name: Set environment
      run: |
        # Add Nix binaries to PATH for subsequent steps
        echo "/home/runner/.nix-profile/bin" >> $GITHUB_PATH
        echo "UV_CACHE_DIR=/tmp/uv-cache" >> "$GITHUB_ENV"
        echo "PATH:"
        echo $PATH
        echo $GITHUB_PATH
      shell: bash

    - name: Restore uv cache
      uses: actions/cache@v4
      with:
        path: ${{ env.UV_CACHE_DIR }}
        key: uv-${{ hashFiles('flake.lock') }}-${{ hashFiles('uv.lock') }}

    - name: Direnv Initialization
      run: |
        direnv allow
        direnv exec . sh -c 'echo $PATH' > "$GITHUB_PATH"
        direnv export gha >> "$GITHUB_ENV"
      shell: bash

    - name: "Prune uv cache (optional)"
      run: uv cache prune --ci || true
      shell: bash
